import os
from dotenv import load_dotenv

load_dotenv()

CONFIG__DATABASE_URL = os.getenv("DATABASE_URL")

CONFIG__SECRET_KEY = os.getenv("CONFIG__SECRET_KEY")
CONFIG__ALGORITHM = os.getenv("CONFIG__ALGORITHM")
CONFIG__ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("CONFIG__ACCESS_TOKEN_EXPIRE_MINUTES")
CONFIG__REFRESH_TOKEN_EXPIRE_DAYS = os.getenv("CONFIG__REFRESH_TOKEN_EXPIRE_DAYS")